name: Playwright Tests

variables:
  CI: true

trigger:
  - main

jobs:
  - job: test
    timeoutInMinutes: 60
    pool:
      vmImage: "ubuntu-latest"

    steps:
      - task: UseNode@1
        inputs:
          versionSpec: "16.x"
          checkLatest: true
        displayName: "Install Node.js"

      - script: |
          npm ci
        displayName: "Install dependencies"
        
      - script: |
          npx playwright install
        displayName: "Install Playwright Browsers"

      - script: |
          npx playwright test tests/UATQuiklyzflow.spec.ts
        displayName: "Run Playwright tests"

      - publish: $(System.DefaultWorkingDirectory)/playwright-report
        artifact: playwright-report

    # Cache Node.js modules to speed up builds
      - task: CacheBeta@2
        inputs:
        key: 'npm | "$(Agent.OS)" | package-lock.json'
        path: $(npm_config_cache)
        cacheHitVar: CACHE_RESTORED
        displayName: Cache Node.js modules
